#ifndef DASHBOARD
#define DASHBOARD

static const char *dashboardHtml =
"<!doctype html>"
"<html lang='en'>"
"  <head>"
"    <meta charset='utf-8' />"
"    <meta name='viewport' content='width=device-width,initial-scale=1' />"
"    <title>ESP Dashboard</title>"
"    <style>"
"      :root {"
"        color-scheme: light dark;"
"        --bg: #0b0f14;"
"        --panel: #121922;"
"        --panel-2: #0f151d;"
"        --text: #e6edf3;"
"        --muted: #93a4b8;"
"        --accent: #2ee6a6;"
"        --accent-2: #57b8ff;"
"        --danger: #ff3b3b;"
"        --danger-dark: #d62a2a;"
"        --warning: #ffb020;"
"        --border: #263243;"
"        --shadow: rgba(0, 0, 0, 0.45);"
"        --glow: rgba(87, 184, 255, 0.25);"
"        --radius: 14px;"
"      }"
""
"      @media (prefers-color-scheme: light) {"
"        :root {"
"          --bg: #f4f7fb;"
"          --panel: #ffffff;"
"          --panel-2: #f0f4f9;"
"          --text: #0f1720;"
"          --muted: #4a5c72;"
"          --accent: #0aa371;"
"          --accent-2: #006dd9;"
"          --danger: #d63636;"
"          --danger-dark: #b12b2b;"
"          --warning: #c47a00;"
"          --border: #d8e0eb;"
"          --shadow: rgba(16, 24, 40, 0.08);"
"          --glow: rgba(0, 109, 217, 0.12);"
"        }"
"      }"
""
"      * {"
"        box-sizing: border-box;"
"      }"
""
"      html,"
"      body {"
"        height: 100%;"
"      }"
""
"      body {"
"        margin: 0;"
"        font-family: 'Segoe UI', 'Tahoma', 'Verdana', sans-serif;"
"        background: radial-gradient(circle at top, rgba(87, 184, 255, 0.12), transparent 45%),"
"          linear-gradient(160deg, var(--bg), #0a0f15 50%, var(--bg));"
"        color: var(--text);"
"        display: grid;"
"        grid-template-rows: auto 1fr auto;"
"        min-height: 100vh;"
"      }"
""
"      header {"
"        padding: 24px clamp(20px, 5vw, 40px);"
"        border-bottom: 1px solid var(--border);"
"        background: linear-gradient(120deg, rgba(46, 230, 166, 0.12), transparent 60%),"
"          var(--panel-2);"
"      }"
""
"      header h1 {"
"        margin: 0 0 6px 0;"
"        font-size: clamp(22px, 2.4vw, 32px);"
"        letter-spacing: 0.02em;"
"      }"
""
"      header p {"
"        margin: 0;"
"        color: var(--muted);"
"        font-size: clamp(12px, 1.4vw, 14px);"
"      }"
""
"      main {"
"        display: grid;"
"        gap: 20px;"
"        padding: 24px clamp(20px, 5vw, 40px) 32px;"
"        grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));"
"        align-items: start;"
"      }"
""
"      section {"
"        background: var(--panel);"
"        border: 1px solid var(--border);"
"        border-radius: var(--radius);"
"        box-shadow: 0 16px 30px var(--shadow);"
"        padding: 18px;"
"      }"
""
"      .controls {"
"        display: grid;"
"        gap: 14px;"
"      }"
""
"      .controls .grid {"
"        display: grid;"
"        grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));"
"        gap: 12px;"
"      }"
""
"      .status-panel {"
"        display: grid;"
"        gap: 12px;"
"      }"
""
"      .status-indicator {"
"        display: flex;"
"        align-items: center;"
"        gap: 12px;"
"        padding: 14px;"
"        border-radius: 12px;"
"        background: linear-gradient(135deg, rgba(46, 230, 166, 0.12), rgba(87, 184, 255, 0.08));"
"        border: 1px solid rgba(87, 184, 255, 0.2);"
"      }"
""
"      .status-dot {"
"        width: 12px;"
"        height: 12px;"
"        border-radius: 50%;"
"        background: var(--warning);"
"        box-shadow: 0 0 12px rgba(255, 176, 32, 0.6);"
"        animation: pulse 1.6s ease-in-out infinite;"
"      }"
""
"      #status {"
"        font-weight: 600;"
"        letter-spacing: 0.02em;"
"      }"
""
"      .meta {"
"        font-size: 12px;"
"        color: var(--muted);"
"      }"
""
"      .logs {"
"        display: grid;"
"        gap: 12px;"
"        grid-column: 1 / -1;"
"      }"
""
"      #logs {"
"        background: #0a0f14;"
"        color: #9cffc0;"
"        border: 1px solid #1e2a36;"
"        border-radius: 12px;"
"        padding: 16px;"
"        min-height: 220px;"
"        max-height: 360px;"
"        overflow: auto;"
"        font-family: 'SFMono-Regular', 'Consolas', 'Liberation Mono', monospace;"
"        font-size: 12px;"
"        line-height: 1.5;"
"        box-shadow: inset 0 0 20px rgba(0, 0, 0, 0.4);"
"      }"
""
"      button {"
"        border: 1px solid transparent;"
"        border-radius: 12px;"
"        padding: 14px 16px;"
"        font-size: 14px;"
"        font-weight: 600;"
"        letter-spacing: 0.02em;"
"        cursor: pointer;"
"        transition: transform 0.12s ease, box-shadow 0.2s ease, background 0.2s ease;"
"        min-height: 48px;"
"        display: inline-flex;"
"        align-items: center;"
"        justify-content: center;"
"        gap: 8px;"
"      }"
""
"      button:focus-visible {"
"        outline: 3px solid var(--accent-2);"
"        outline-offset: 2px;"
"      }"
""
"      button:active {"
"        transform: translateY(1px) scale(0.98);"
"      }"
""
"      .btn {"
"        background: var(--panel-2);"
"        color: var(--text);"
"        border: 1px solid var(--border);"
"        box-shadow: 0 10px 18px var(--shadow);"
"      }"
""
"      .btn:hover {"
"        box-shadow: 0 12px 20px var(--shadow), 0 0 0 1px var(--glow);"
"      }"
""
"      .btn-stop {"
"        background: linear-gradient(140deg, var(--danger), var(--danger-dark));"
"        color: #fff;"
"        border: 1px solid rgba(255, 59, 59, 0.5);"
"        box-shadow: 0 14px 26px rgba(255, 59, 59, 0.4);"
"        font-size: 16px;"
"      }"
""
"      .btn-stop:hover {"
"        box-shadow: 0 16px 30px rgba(255, 59, 59, 0.55);"
"      }"
""
"      .btn-primary {"
"        background: linear-gradient(140deg, rgba(46, 230, 166, 0.85), rgba(87, 184, 255, 0.85));"
"        color: #031018;"
"        border: none;"
"      }"
""
"      .btn-secondary {"
"        background: rgba(87, 184, 255, 0.12);"
"        color: var(--text);"
"        border: 1px solid rgba(87, 184, 255, 0.35);"
"      }"
""
"      .btn-warning {"
"        background: rgba(255, 176, 32, 0.12);"
"        color: var(--text);"
"        border: 1px solid rgba(255, 176, 32, 0.4);"
"      }"
""
"      footer {"
"        padding: 18px clamp(20px, 5vw, 40px);"
"        border-top: 1px solid var(--border);"
"        color: var(--muted);"
"        font-size: 12px;"
"        display: flex;"
"        justify-content: space-between;"
"        gap: 12px;"
"        flex-wrap: wrap;"
"      }"
""
"      @keyframes pulse {"
"        0% {"
"          transform: scale(0.9);"
"          opacity: 0.6;"
"        }"
"        50% {"
"          transform: scale(1.15);"
"          opacity: 1;"
"        }"
"        100% {"
"          transform: scale(0.9);"
"          opacity: 0.6;"
"        }"
"      }"
""
"      @media (max-width: 720px) {"
"        header {"
"          padding-top: 20px;"
"        }"
""
"        main {"
"          padding-top: 18px;"
"        }"
""
"        .controls .grid {"
"          grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));"
"        }"
"      }"
"    </style>"
"  </head>"
"  <body>"
"    <header>"
"      <h1>Mark Suck a Berg - Dashboard</h1>"
"    </header>"
"    <main>"
"      <section class='controls' aria-label='Controls'>"
"        <h2>Controls</h2>"
"        <div class='grid'>"
"          <button id='stop' class='btn-stop' aria-label='Stop Gantry'>Stop</button>"
"          <button id='run' class='btn btn-primary' aria-label='Run Program'>Run</button>"
"          <button id='pause' class='btn btn-warning' aria-label='Pause Gantry'>Pause</button>"
"          <button id='home' class='btn btn-secondary' aria-label='Home Gantry'>Home</button>"
"        </div>"
"      </section>"
""
"      <section class='status-panel' aria-label='System Status'>"
"        <h2>System Status</h2>"
"        <div class='status-indicator'>"
"          <span class='status-dot' aria-hidden='true'></span>"
"          <div>"
"            <div id='status'>Status: unknown</div>"
"            <div class='meta'>Monitoring motion controller and safety interlocks.</div>"
"          </div>"
"        </div>"
"      </section>"
""
"      <section class='logs' aria-label='Live Logs'>"
"        <h2>Live Logs</h2>"
"        <pre id='logs' aria-live='polite'></pre>"
"      </section>"
"    </main>"
"    <footer>"
"      <span>Gantry Control · Build 1.0</span>"
"      <span>Network: Local ESP32</span>"
"    </footer>"
""
"    <script>"
"      const statusEl = document.getElementById('status');"
"      const logsEl = document.getElementById('logs');"
""
"      async function refresh() {"
"        const r = await fetch('/status');"
"        const j = await r.json();"
"        const states = ['running', 'paused', 'stopped', 'homing'].filter("
"          (key) => j[key] === true"
"        );"
"        const s = states.length ? states.join(', ') : 'idle';"
"        statusEl.textContent = 'Status: ' + s;"
"      }"
""
"      async function refreshLogs() {"
"        const r = await fetch('/logs');"
"        const t = await r.text();"
"        logsEl.textContent = t;"
"        logsEl.scrollTop = logsEl.scrollHeight;"
"      }"
""
"      const post = (p) => fetch(p, { method: 'POST' }).then(refresh);"
""
"      document.getElementById('run').onclick = () => post('/run');"
"      document.getElementById('stop').onclick = () => post('/stop');"
"      document.getElementById('home').onclick = () => post('/home');"
"      document.getElementById('pause').onclick = () => post('/pause');"
""
"      setInterval(refresh, 1000);"
"      setInterval(refreshLogs, 1000);"
"      refresh();"
"      refreshLogs();"
"    </script>"
"  </body>"
"</html>";

#endif